application: lets-talky-talky
version: 1
runtime: python
api_version: 1

handlers:

- url: /admin\.html
  #script: admin.html
  static_files: admin.html
  upload: admin.html
- url: .*
  script: main.py

- url: /ckeditor
  static_dir: ckeditor
